# Site settings
title: jesse larusso - web developer
email: jesselarusso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlarusso.github.io" # the base hostname & protocol for your site
twitter_username: jesselarusso
github_username:  jlarusso
timezone: America/New_York

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['footnotes']
highlighter: pygments
