# Site settings
title: Jesse La Russo
email: jesselarusso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Who is Jesse La Russo?  Doesn't have the same ring as Keyser Söze,
  but that's an unfair comparison.  There's no movie about me. If
  there was, it would start with a heated discussion about current
  events.  The rising action would include my quest for the
  elusive perfect data API.  The climax would be me raising my
  hackathon trophy up above a roaring crowd.  I awaken realizing
  it was all a dream.  The resolution- I grab my laptop and try
  recording all that brilliant code I dreamt up.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlarusso.github.io" # the base hostname & protocol for your site
twitter_username: jesselarusso
github_username:  jlarusso
timezone: America/New_York

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['footnotes']
highlighter: pygments
